version: '3.3'
services:
    tesla-service:
        build: .
        ports:
            - '8000:8000'
        image: tesla-service
        networks:
          - app_sail
networks:
  app_sail:
    external:
        name: app_sail