version: '3.3'
services:
    mock-tesla-service:
        build: .
        ports:
            - '8001:8001'
        image: tesla-mock-service
        networks:
          - app_sail
networks:
  app_sail:
    external:
        name: app_sail
